// packages/playground/src/components/Counter.vue
<script setup lang="ts">
import { ref } from 'vue/vapor'

const emits = defineEmits<{ (e: 'increment', value: number): void }>()

const count = ref(0)
function increment(e: Event) {
  console.log('increment vue', e)
  count.value++
  emits('increment', count.value)
}
</script>

<template>
  <div id="vue" class="box">
    <button class="vue" type="button" @click="increment">Vue Vapor count is {{ count }}</button>
    <br>
    <slot />
  </div>
</template>

// packages/playground/src/components/Counter.svelte
<script>
  import { createEventDispatcher, onMount } from 'svelte'

  let count = 0
  const dispatch = createEventDispatcher()

  onMount(() => {
    console.log('Svelte Vapor component mounted')
  })

  function increment() {
    count += 1
    dispatch('increment', { count: count })
  }
</script>

<div class="box" id="svelte">
  <button on:click={increment}>
    Svelte Vapor count is {count}
  </button>
  <br />
  <slot></slot>
</div>
