// packages/playground/src/components/Counter.vue
<script setup lang="ts">
import { ref } from 'vue/vapor'

const count = ref(0)
</script>

<template>
  <div class="card">
    <button
      type="button"
      @click="count++"
    >
      Vue Vapor count is {{ count }}
    </button>
  </div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

// packages/playground/src/components/Counter.tsx
import { useState } from 'react'

function Counter(): JSX.Element {
  const [count, setCount] = useState(0)
  return (
    <div id="react">
      <button onClick={() => setCount(count + 1)}>React Vapor count is {count}</button>
      <br />
      <span>This is a React component</span>
    </div>
  )
}
export default Counter
